---
- name: Add debian non-free repositories
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  register: apt_sources
  become: yes

- name: Upgrade debian distribution
  when: apt_sources.changed
  block:
    - name: Apt update cache
      apt:
        update_cache: yes

    - name: Apt full upgrade
      apt:
        upgrade: full

    - name: Apt autoremove
      apt:
        autoremove: yes
  become: yes

- name: Configure apt to not install recommended packages
  lineinfile:
    path: /etc/apt/apt.conf.d/01norecommends
    line: 'APT::Install-Recommends "0";'
    state: present
    create: true
    mode: '0644'
  become: yes
