---
- block:
    - name: Check if 32 bit packages are enabled
      shell: dpkg --print-foreign-architectures | grep i386

  rescue:
    - name: Enable 32 bit packages
      command: dpkg --add-architecture i386

    - name: Install steam
      apt:
        name:
          - steam-installer
          - mesa-vulkan-drivers
          - libglx-mesa0:i386
          - mesa-vulkan-drivers:i386
          - libgl1-mesa-dri:i386
        state: present
        install_recommends: no
        update_cache: yes

    - name: Add user video and audio groups
      user:
        name: "{{ USER }}"
        groups: video,audio
        append: yes
  become: yes
