---
- name: Copy distribution dotfiles
  copy:
    src: dotfiles/
    dest: "{{ HOME }}/"

- name: Template gtk bookmarks
  template:
    src: bookmarks.j2
    dest: "{{ HOME }}/.config/gtk-3.0/bookmarks"
    mode: '0644'

- name: Copy system config files
  copy:
    src: system/
    dest: /
  become: yes

- name: Make custom binaries executable
  file:
    path: /usr/local/bin/
    mode: '0755'
    recurse: yes
  become: yes

- name: Enable systemd user units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop: "{{ systemd_user_units }}"

- name: Start and enable systemd system units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ systemd_system_units }}"
  become: yes

- name: Add user to groups
  user:
    name: "{{ USER }}"
    groups: "{{ user_groups }}"
  become: yes

- name: Create user dirs
  file:
    path: "{{ HOME }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ user_dirs }}"

# - name: Check if local dotfiles repo already exists
#   stat:
#     path: "{{ HOME }}/dotfiles"
#   register: dotfiles

# - name: Clone/update dotfiles repo
#   git:
#     repo: https://github.com/basharkey/dotfiles.git
#     dest: "{{ HOME }}/dotfiles"

# - name: Set dotfiles repo remote origin to SSH URI
#   command: git remote set-url origin git@github.com:basharkey/dotfiles.git
#   args:
#     chdir: "{{ HOME }}/dotfiles"

# - name: Copy user dotfiles
#   when: not dotfiles.stat.isdir is defined
#   command: "./install.sh -e user"
#   args:
#     chdir: "{{ HOME }}/dotfiles"

# - name: Copy user dotfiles with overrides
#   when: not dotfiles.stat.isdir is defined and override is defined
#   command: "./install.sh -e user -o {{ override }}"
#   args:
#     chdir: "{{ HOME }}/dotfiles"

# - name: Copy system dotfiles
#   when: not dotfiles.stat.isdir is defined
#   command: "./install.sh -e system"
#   args:
#     chdir: "{{ HOME }}/dotfiles"
#   become: yes

# - name: Copy system dotfiles with overrides
#   when: not dotfiles.stat.isdir is defined and override is defined
#   command: "./install.sh -e system -o {{ override }}"
#   args:
#     chdir: "{{ HOME }}/dotfiles"
#   become: yes

- name: Run lm-sensors auto detection for i3block temperature module
  command: sensors-detect --auto
  become: yes

- name: Install custom scripts
  include_tasks:
    file: scripts.yml

- name: Setup bose qc 35 ii easyeffects udev rules
  template:
    src: 50-bose-qc-35-ii.rules.j2
    dest: /etc/udev/rules.d/50-bose-qc-35-ii.rules
    mode: '0644'
  notify:
    - Reload udev rules
  become: yes

- name: Change default target to multi-user.target
  file:
    src: /usr/lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link
  become: yes

- name: Create getty service overrides directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'
  become: yes

- name: Template getty service autologin config
  template:
    src: autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    mode: '0644'
  become: yes
