---
- name: Install wayweather dependencies
  apt:
    name:
      - python3
      - python3-yaml
      - python3-bs4
    state: present
    install_recommends: no
  become: yes

- name: Install wayweather
  get_url:
    url: https://raw.githubusercontent.com/basharkey/wayweather/main/wayweather.py
    dest: /usr/local/bin/wayweather.py
    mode: '0755'
  become: yes

- name: Check if music scripts are installed
  stat:
    path: "/usr/local/bin/{{ item }}"
  register: "{{ item }}"
  loop:
    - "playlist_add_album.py"
    - "process_album.py"

- name: Install music scripts
  when: not "playlist_add_album.py".exists or not "process_album.py".exists
  block:
    - name: Clone repo
      git:
        repo: https://github.com/basharkey/music-processing-scripts.git
        dest: /tmp/music-processing-scripts

    - name: Run make install
      command: make install
      args:
        chdir: /tmp/music-processing-scripts
      become: yes
    

