---
debian_packages:
  # Desktop environment
  - "xserver-xorg"                       # X11 server
  - "xinit"                              # startx
  - "x11-xserver-utils"                  # xrandr
  - "x11-utils"                          # xkill
  - "linux-headers-amd64"                # Linux headers for compiling kernel modules
  - "i3-wm"                              # i3 tiling window manager
  - "i3blocks"                           # Hacker friendly i3status
  - "libanyevent-i3-perl"                # i3-save-tree dependency
  - "lm-sensors"                         # i3blocks temperature module dependency
  - "sysstat"                            # i3blocks cpu_usage module dependency
  - "i3lock"                             # i3 screen locker
  - "xss-lock"                           # Auto screen locker
  - "rofi"                               # Application launcher and dmenu replacement
  - "redshift"                           # Adjust screen colour temperature based on time
  - "dunst"                              # Notification daemon
  - "suckless-tools"                     # Minimal tools for window managers
  - "alacritty"                          # OpenGL terminal emulator
  - "mate-polkit-bin"                    # MATE authentication agent for PolicyKit-1
  - "xdg-desktop-portal-gnome"           # Fixes Flatpaks not being able to access dbus

  # CLI utilities
  - "vim"                                # vim
  - "git"                                # git
  - "curl"                               # curl
  - "traceroute"                         # traceroute
  - "plocate"                            # Faster version of mlocate
  - "7zip"                               # 7zip
  - "rsync"                              # rsync
  - "pciutils"                           # lspci
  - "wireguard-tools"                    # Fast, modern, secure VPN tunnel
  - "usbutils"                           # lsusb
  - "cifs-utils"                         # Utilities for mounting and managing CIFS mounts
  - "bind9-utils"                        # Utilities for querying DNS name servers
  - "python3"                            # python
  - "python3-pip"                        # python package manager
  - "python3-venv"                       # Python virtual environment module
  - "python3-virtualenv"                 # Tool to create isolated Python environments
  - "pandoc"                             # Conversion between markup formats
  - "podman"                             # Manage Pods, Containers and Container Images
  - "aardvark-dns"                       # Container-focused DNS server
  - "rootlesskit"                        # podman dependency
  - "slirp4netns"                        # podman dependency
  - "fuse-overlayfs"                     # podman overlay storage driver
  - "progress"                           # Coreutils Viewer
  - "libglib2.0-bin"                     # gio
  - "yt-dlp"                             # YouTube downloader
  - "ffmpeg"                             # ffmpeg
  - "jq"                                 # lightweight and flexible command-line JSON processor
  - "ntfs-3g"                            # read/write NTFS driver for FUSE

  # Sound server
  - "pipewire"                           # Media server
  - "pipewire-pulse"                     # PipeWire PulseAudio plugin
  - "wireplumber"                        # PipeWire session manager
  - "libspa-0.2-bluetooth"               # PipeWire bluetooth libraries
  - "firmware-realtek"                   # Binary firmware for Realtek wired/wifi/BT adapters
  - "pulseaudio-utils"                   # pactl
  - "pavucontrol"                        # pavucontrol
  - "playerctl"                          # playerctl
  - "easyeffects"                        # PipeWire equalizer
  - "lsp-plugins-lv2"                    # easyeffects equalizer dependency

  # Themes and fonts
  - "gnome-themes-extra"                 # Adwaita-dark
  - "adwaita-icon-theme-legacy"          # Fallback icons for legacy applications
  - "adwaita-qt"                         # Adwaita Qt5 theme
  - "adwaita-qt6"                        # Adwaita Qt6 theme
  - "qt5ct"                              # Qt5 Configuration Tool
  - "qt6ct"                              # Qt6 Configuration Tool
  - "qt6-svg-plugins"                    # breeze-icon-theme dependency
  - "fonts-noto-cjk"
  - "fonts-noto-cjk-extra"
  - "fonts-noto-color-emoji"
  - "fonts-noto-core"
  - "fonts-noto-extra"
  - "fonts-noto-mono"
  - "fonts-noto-ui-core"
  - "fonts-noto-ui-extra"
  - "fonts-noto-unhinted"

  # GUI applications
  - "firefox-esr"                        # Firefox
  - "pcmanfm-qt"                         # File manager
  - "xarchiver"                          # Unzip utility for GTK file managers
  - "gvfs-fuse"                          # gvfs
  - "gvfs-backends"                      # SMB, MTP backends for fuse
  - "eject"                              # Ejects CDs and operates CD-Changers under Linux
  - "ffmpegthumbnailer"                  # Fast and lightweight video thumbnailer
  - "kdenlive"                           # non-linear video editor
  - "mediainfo"                          # kdenlive dependency
  - "frei0r-plugins"                     # kdenlive dependency
  - "mpv"                                # Video player
  - "flatpak"                            # Application deployment framework for desktop apps
  - "evolution"                          # Email client
  - "evolution-ews"                      # Evolution extension for Exchange Web Services
  - "keepassxc"                          # Password manager
  - "seahorse"                           # GTK keyring manager
  - "gnome-keyring"                      # Gnome keyring daemon
  - "blueman"                            # GTK bluetooth manager
  - "libreoffice"                        # Office suite
  - "libreoffice-qt6"                    # LibreOffice qt6 integration
  - "hunspell-en-ca"                     # English (Canada) dictionary for hunspell
  - "gimp"    				 # Photo editor
  - "feh"    			         # Image viewer
  - "evince"    			 # PDF viewer
  - "syncthing"                          # Decentralized file synchronization
  - "strawberry"                         # Audio player and music collection organizer
  - "gstreamer1.0-libav"                 # ffmpeg plugin for gstreamer (enable playing m4a files)
  - "gscan2pdf"                          # GUI for producing a multipage PDF from a scan
  - "djvulibre-bin"                      # gscan2pdf dependency
  - "pdftk"                              # gscan2pdf dependency
  - "unpaper"                            # gscan2pdf dependency
  - "sane-airscan"                       # Required for sane scanning over IP
  - "cups"                               # CUPS printing daemon
  - "printer-driver-brlaser"             # Brother printer drivers
  - "emacs"                              # The best text editor
  - "libsqlite3-dev"                     # Emacs magit dependency
  - "gcc"                                # Needed to build sqlite3-api module for emacs
  - "flameshot"                          # Screenshot tool

flatpak_packages:
  - "com.spotify.Client"                 # Online music streaming service
  - "com.discordapp.Discord"             # Messaging, Voice, and Video Client
  - "io.github.spacingbat3.webcord"      # A Discord and Fosscord web-based client made with the electron
  - "org.musicbrainz.Picard"             # MusicBrainz's music tagger
  - "org.gnome.gitlab.dqpb.GMetronome"   # Metronome
  - "org.chromium.Chromium"              # The web browser from Chromium project
