---
- name: Apt update cache
  apt:
    update_cache: yes
  become: yes

- name: Apt full upgrade
  apt:
    upgrade: full
  become: yes

- name: Apt autoremove
  apt:
    autoremove: yes
  become: yes
