---
- name: Install qemu/kvm
  apt:
    name:
      - qemu-system                # QEMU system emulation binaries
      - libvirt-daemon-system      # libvirt daemon
      - dnsmasq                    # libvirt networking dependency
      - ovmf                       # UEFI firmware for virtual machines
      - qemu-utils                 # QEMU utilities
      - virt-manager               # GTK virtual machine manager
      - gir1.2-spiceclientgtk-3.0  # virt-manager spice viewer dependency
    state: present
    install_recommends: no
  become: yes

- name: Grub enable IOMMU
  block:
    - name: Check if IOMMU enabled in grub config
      command: egrep "(amd|intel)_iommu=on" /etc/default/grub
  rescue:
    - name: Grub enable AMD IOMMU
      command: sed -i 's|GRUB_CMDLINE_LINUX="[^"]*|& amd_iommu=on|g' /etc/default/grub
      when: ansible_processor[1] == "AuthenticAMD"

    - name: Grub enable Intel IOMMU
      command: sed -i 's|GRUB_CMDLINE_LINUX="[^"]*|& intel_iommu=on|g' /etc/default/grub
      when: ansible_processor[1] == "GenuineIntel"

    - name: Write grub config
      command: update-grub
  become: yes

- name: Template QEMU config
  template:
    src: qemu.conf.j2
    dest: /etc/libvirt/qemu.conf
    mode: '0644'
  become: yes

- name: Start and enable libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  become: yes

- name: Enable default nat libvirt network at boot
  command: virsh net-autostart default
  become: yes

- name: Copy vfio modules config
  copy:
    src: vfio-modules.conf
    dest: /etc/modules-load.d/vfio.conf
  notify: Update initramfs
  become: yes

- name: Template vfio module options config
  template:
    src: vfio-options.conf.j2
    dest: /etc/modprobe.d/vfio.conf
    mode: '0644'
  notify: Update initramfs
  become: yes

- name: Create virtio-win dir
  file:
    path: /var/lib/libvirt/virtio-win
    state: directory
    mode: '0755'
  become: yes

- name: Download virtio-win drivers ISO
  get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
    dest: /var/lib/libvirt/virtio-win/virtio-win.iso
    mode: '0644'
  become: yes
