---
- name: Install bridge-utils
  apt:
    name: bridge-utils
    state: present
    install_recommends: no
  become: yes

- name: Copy br_netfilter kernel module config
  copy:
    src: br_netfilter.conf
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: '0644'
  become: yes

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present
  become: yes

- name: Copy br_netfilter kernel variable config
  copy:
    src: 99-netfilter-bridge.conf
    dest: /etc/sysctl.d/99-netfilter-bridge.conf
    mode: '0755'
  become: yes

- name: Reload all kernel variables
  systemd:
    name: systemd-sysctl.service
    state: restarted
  become: yes

- name: Check if bridge adapter is already the primary interface
  when: bridge_interface != ansible_default_ipv4.interface
  block:
    - name: Template bridge network interfaces config
      template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        mode: '0644'
      become: yes

    - name: Restart networking service
      systemd:
        name: networking.service
        state: restarted
      become: yes

- name: Ensure libvirtd is running
  systemd:
    name: libvirtd.service
    state: started
  become: yes

- name: Generate libvirt bridge network definition var
  template:
    src: bridge-network.xml.j2
    dest: /tmp/bridge-network.xml
    mode: '0644'

- name: Add libvirt bridge network definition
  shell: virsh net-define /tmp/bridge-network.xml
  register: result
  failed_when: result.rc != 0 and "network '" ~ bridge_libvirt_network ~ "' already exists" not in result.stderr
  become: yes

- name: Enable libvirt bridge network at boot
  command: "virsh net-autostart {{ bridge_libvirt_network }}"
  become: yes

- name: Start libvirt bridge network
  command: "virsh net-start {{ bridge_libvirt_network }}"
  register: result
  failed_when: result.rc != 0 and "network is already active" not in result.stderr
  become: yes
